---
- name: Rocky Linux | add kernel modules
  community.general.ini_file:
    option: "{{ item }}"
    state: present
    path: "/etc/modules-load.d/{{ os_service_name }}.conf"
    section: ""
    mode: "0644"
    allow_no_value: true
  loop:
    - br_netfilter
  become: true

- name: Rocky Linux | systemctl restart systemd-modules-load
  ansible.builtin.systemd:
    name: "systemd-modules-load.service"
    state: "restarted"
    enabled: true
  become: true
  register: restart_systemd_service
  failed_when: restart_systemd_service.failed

- name: Rocky Linux | Install prerequisite packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ pkg_state }}"
  register: _pkg
  until: not _pkg.failed
  retries: 3
  delay: 3
  loop: "{{ prereq_pkgs }}"
  become: true

- name: Rocky Linux | enable powertools repo
  ansible.builtin.command: >-
    dnf config-manager --set-enabled powertools
  become: true

- name: Rocky Linux | add openstack repository
  ansible.builtin.command: >-
    dnf -y install {{ openstack_repo_rpm }}
  become: true

- name: Rocky Linux | Install controller packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ pkg_state }}"
  register: _pkg
  until: not _pkg.failed
  retries: 3
  delay: 3
  become: true
  loop: "{{ controller_packages }}"
  when: inventory_hostname in groups['controller']

- name: Rocky Linux | Install compute packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ pkg_state }}"
  register: _pkg
  until: not _pkg.failed
  retries: 3
  delay: 3
  become: true
  loop: "{{ compute_packages }}"
  when: inventory_hostname in groups['compute']
...
