---
- name: systemctl restart systemd-modules-load.service
  ansible.builtin.service:
    name: "systemd-modules-load.service"
    state: "restarted"
  register: _restart_service
  until: _restart_service.state == "started"
  retries: 3
  delay: 3
  become: true
  changed_when: false

- name: systemctl restart service
  ansible.builtin.service:
    name: "{{ item }}"
    state: "restarted"
    enabled: true
  register: _restart_service
  until: _restart_service.state == "started"
  retries: 3
  delay: 3
  become: true
  changed_when: false
  loop: "{{ os_systemd_service_name }}"

- name: systemctl restart compute service
  ansible.builtin.service:
    name: "{{ item }}"
    state: "restarted"
    enabled: true
  register: _restart_service
  until: _restart_service.state == "started"
  retries: 3
  delay: 3
  become: true
  changed_when: false
  loop: "{{ os_systemd_compute_service_name }}"
...
